export const livesData1 = {
    "data":[
        {
            "avatar":"img/avatar.jpg",
            "involvement":7,
            "title":"如何发现特别的城市探索路线？",
            "author":"明哥"
        },
        {
            "avatar":"img/avatar.jpg",
            "involvement":7,
            "title":"如何发现特别的城市探索路线？",
            "author":"明哥"
        },
        {
            "avatar":"img/avatar.jpg",
            "involvement":7,
            "title":"如何发现特别的城市探索路线？",
            "author":"明哥"
        },
        {
            "avatar":"img/avatar.jpg",
            "involvement":7,
            "title":"如何发现特别的城市探索路线？",
            "author":"明哥"
        }
    ],
    "total":10
}
export const livesData2 = {
    "data":[
        {
            "avatar":"https://pic3.zhimg.com/9d24e742e0ce3272dee199b9620a201a_s.jpg",
            "involvement":30,
            "title":"如何在技术上持续精进",
            "author":"forunk"
        },
        {
            "avatar":"https://pic3.zhimg.com/9d24e742e0ce3272dee199b9620a201a_s.jpg",
            "involvement":30,
            "title":"如何在技术上持续精进",
            "author":"forunk"
        },
        {
            "avatar":"https://pic3.zhimg.com/9d24e742e0ce3272dee199b9620a201a_s.jpg",
            "involvement":30,
            "title":"如何在技术上持续精进",
            "author":"forunk"
        },
        {
            "avatar":"https://pic3.zhimg.com/9d24e742e0ce3272dee199b9620a201a_s.jpg",
            "involvement":30,
            "title":"如何在技术上持续精进",
            "author":"forunk"
        }

    ],
    "total":10
}